// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79ZKb5fZMdZ-Y8YTAoQuusV77EmflxaY',
    appId: '1:191609577202:web:70dd39bda0207a22747a6b',
    messagingSenderId: '191609577202',
    projectId: 'kosanku-4fad1',
    authDomain: 'kosanku-4fad1.firebaseapp.com',
    databaseURL: 'https://kosanku-4fad1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosanku-4fad1.firebasestorage.app',
    measurementId: 'G-HJF4M5XKBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6tMbknji3kwwUMUCJUtgNd1FLHdEj-8',
    appId: '1:191609577202:android:5b3ab26e4ed8052d747a6b',
    messagingSenderId: '191609577202',
    projectId: 'kosanku-4fad1',
    databaseURL: 'https://kosanku-4fad1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosanku-4fad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmA7Teh6pxPBHQMrc2MqwklySJ51TymGM',
    appId: '1:191609577202:ios:56409275f01f8776747a6b',
    messagingSenderId: '191609577202',
    projectId: 'kosanku-4fad1',
    databaseURL: 'https://kosanku-4fad1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosanku-4fad1.firebasestorage.app',
    iosBundleId: 'com.example.kosanKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmA7Teh6pxPBHQMrc2MqwklySJ51TymGM',
    appId: '1:191609577202:ios:56409275f01f8776747a6b',
    messagingSenderId: '191609577202',
    projectId: 'kosanku-4fad1',
    databaseURL: 'https://kosanku-4fad1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosanku-4fad1.firebasestorage.app',
    iosBundleId: 'com.example.kosanKu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA79ZKb5fZMdZ-Y8YTAoQuusV77EmflxaY',
    appId: '1:191609577202:web:99b1b4335c50b79a747a6b',
    messagingSenderId: '191609577202',
    projectId: 'kosanku-4fad1',
    authDomain: 'kosanku-4fad1.firebaseapp.com',
    databaseURL: 'https://kosanku-4fad1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosanku-4fad1.firebasestorage.app',
    measurementId: 'G-D6K53V4X3L',
  );
}